const data = [
    {
        id : 1,
        city:"Noida",
        heading:"Shop in Sector-61, Noida for Rent",
        place:"Hoshiyarpur, Near Shivalik Hosoital",
        rent:"65000",
        deposit:"2.5 Lacs",
        builtup:"900 sqft",
        propertyType:"Shop",
        parking:"public",
        furnishing:"Semi-Furnished",
        available:"Immediately",
        image:"https://urbanupdate.in/wp-content/uploads/2018/07/GNHR.jpg"
    },
    {
        id: 2,
        city:"Noida",
        heading:"Flat in Sector-52, Noida for Rent",
        place:"Parichowk",
        rent:"20000",
        deposit:"20000 ",
        builtup:"400 sqft",
        propertyType:"Flat",
        parking:"Private",
        furnishing:"Semi-Furnished",
        available:"Immediately",
        image:"https://images.livemint.com/img/2022/08/25/600x338/PTI08-24-2022-000144A-0_1661388301859_1661388301859_1661388336302_1661388336302.jpg"
    },
    {
        id:3,
        city:"Noida",
        heading:"Flat in Ghazipur, Noida for Rent",
        place:"Ghazipur",
        rent:"15000",
        deposit:"15000 Lacs",
        builtup:"350 sqft",
        propertyType:"Flat",
        parking:"Private",
        furnishing:"Fully-Furnished",
        available:"Immediately",
        image:"https://images.hindustantimes.com/rf/image_size_640x362/HT/p2/2016/11/02/Pictures/_70e99812-a0bd-11e6-8b09-4d35dc1d77aa.jpg"
    },
    {
        id:4,
        city:"Noida",
        heading:"Shop in Vijaynagar, Ghaziabad for Rent",
        place:"Vijaynagar",
        rent:"55000",
        deposit:"1.9 Lacs",
        builtup:"8500 sqft",
        propertyType:"Shop",
        parking:"public",
        furnishing:"Fully-Furnished",
        available:"Immediately",
        image:"https://imgs.nestimg.com/5_bhk_apartment_in_sector_94_for_resale_noida_the_reference_number_is_13009372_6810011702809998649.jpg"
    },
    {
        id:5,
        city:"Noida",
        heading:"Shop in Govindpuram, Ghaziabad for Rent",
        place:"Govindpuram",
        rent:"47000",
        deposit:"2.6 Lacs",
        builtup:"780 sqft",
        propertyType:"Shop",
        parking:"Private",
        furnishing:"Semi-Furnished",
        available:"Immediately",
        image:"https://content.jdmagicbox.com/comp/noida/l4/011pxx11.xx11.181113202325.z7l4/catalogue/jaypee-kalypso-court-noida-residential-buildings-03agiysmh2.jpg"
    },
    {
        id:6,
        city:"Noida",
        heading:"Shop in Sector-52, Noida for Rent",
        place:"Sector-52",
        rent:"33000",
        deposit:"2 Lacs",
        builtup:"400 sqft",
        propertyType:"Shop",
        parking:"Private",
        furnishing:"Semi-Furnished",
        available:"Immediately",
        image:"https://content.jdmagicbox.com/comp/noida/l4/011pxx11.xx11.181113202325.z7l4/catalogue/jaypee-kalypso-court-noida-residential-buildings-1btspvyypi.jpg"
    },
    {
        id:7,
        city:"Noida",
        heading:"Shop in Sector-52, Noida for Rent",
        place:"Sector-52",
        rent:"33000",
        deposit:"2 Lacs",
        builtup:"400 sqft",
        propertyType:"Shop",
        parking:"Private",
        furnishing:"Semi-Furnished",
        available:"Immediately",
        image:"https://content.jdmagicbox.com/comp/noida/l4/011pxx11.xx11.181113202325.z7l4/catalogue/jaypee-kalypso-court-noida-residential-buildings-1btspvyypi.jpg"
    },
    {
        id:8,
        city:"Noida",
        heading:"Shop in Sector-52, Noida for Rent",
        place:"Sector-52",
        rent:"33000",
        deposit:"2 Lacs",
        builtup:"400 sqft",
        propertyType:"Shop",
        parking:"Private",
        furnishing:"Semi-Furnished",
        available:"Immediately",
        image:"https://content.jdmagicbox.com/comp/noida/l4/011pxx11.xx11.181113202325.z7l4/catalogue/jaypee-kalypso-court-noida-residential-buildings-1btspvyypi.jpg"
    }
]

export default data